[project]
name = 'NFT-Lending-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.NFTL]
path = 'contracts/NFTL.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[contracts.achievement-system]
path = 'contracts/achievement-system.clar'
clarity_version = 3
epoch = 3.1

[contracts.credit-scoring]
path = 'contracts/credit-scoring.clar'
clarity_version = 3
epoch = 3.1

[repl.achievement-system]
passes = ['check_checker']

[repl.credit-scoring]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
